title: Envelist
tagline: Print multiple envelopes for free in your browser
author:
  name: Matthew Miner
  email: mminer237@gmail.com
  site: https://matthewminer.name
url: https://envelist.net
# tagManagerCode: GTM-TK37G57
# googleAdClient: ca-pub-5576042369154755
lightThemeColor: "#F17BA7"
darkThemeColor: "#954C68"

googleFonts:
  - Roboto:500

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

collections:
  pages:
    output: true
    permalink: /:name

permalink: /:name

sass:
  style: compressed

plugins:
  - jekyll-sitemap
